// ── Mukth Design Tokens ─────────────────────────────────────────────────────
export const C = {
  // Emerald green family
  g900:  '#011a12',
  g850:  '#022c22',
  g800:  '#064e3b',   // Primary brand
  g700:  '#065f46',
  g600:  '#047857',
  g500:  '#059669',
  g100:  '#d1fae5',
  g50:   '#ecfdf5',

  // Gold / Sand
  gold:  '#d4af37',   // Secondary brand
  goldD: '#b8941f',
  goldL: '#f0dc80',
  gold50:'#fffbea',

  // Neutrals
  white: '#ffffff',
  offW:  '#fafaf8',   // Page background
  dark:  '#0c1810',
  muted: '#4a6358',
  border:'#cde5d7',
  borderL:'#e8f4ef',

  // WhatsApp
  wa: '#25D366',
};

// ── WhatsApp number — !! REPLACE WITH YOUR NUMBER !! ─────────────────────────
export const WHATSAPP_NUMBER = '201220610310';

// ── Navigation links ─────────────────────────────────────────────────────────
export const NAV_LINKS = [
  { href: '#home',        label: 'الرئيسية',   labelEn: 'Home' },
  { href: '#about',       label: 'من نحن',     labelEn: 'About Us' },
  { href: '#curricula',   label: 'المناهج',    labelEn: 'Curricula' },
  { href: '#pricing',     label: 'الأسعار',    labelEn: 'Pricing' },
  { href: '#teachers',    label: 'معلمونا',    labelEn: 'Teachers' },
  { href: '#contact',     label: 'تواصل معنا', labelEn: 'Contact' },
];

// ── Curricula data ────────────────────────────────────────────────────────────
export const CURRICULA = [
  {
    id: 'kids',
    icon: '🌱',
    title: 'حفظ للأطفال',
    titleEn: 'Kids Memorization',
    ageRange: '٦ – ١٤ سنة',
    ageRangeEn: '6 – 14 Years',
    color: '#e8f7f0',
    accent: '#047857',
    desc: 'منهج مرحلي خاص بالأطفال يجمع بين الحفظ واللعب التعليمي، مع تتبّع تقدم الطفل بشكل أسبوعي.',
    descEn: 'A phased curriculum for children combining memorization with educational play and weekly tracking.',
    features: ['حصص ترفيهية تفاعلية', 'تقرير أسبوعي للوالدين', 'معلمات متخصصات بالأطفال', 'تحفيز وشهادات تقدير'],
    featuresEn: ['Interactive leisure classes', 'Weekly parent reports', 'Specialized child teachers', 'Rewards and certificates'],
  },
  {
    id: 'adults',
    icon: '📖',
    title: 'حفظ للكبار',
    titleEn: 'Adult Memorization',
    ageRange: '١٥+ سنة',
    ageRangeEn: '15+ Years',
    color: '#faf6e8',
    accent: '#b8941f',
    desc: 'خطة حفظ منظمة للبالغين مع جداول دراسية مرنة تناسب المشغولين، ومراجعة دورية مستمرة.',
    descEn: 'Organized memorization plans for adults with flexible schedules and periodic reviews.',
    features: ['جداول مرنة على مدار اليوم', 'خطة حفظ شخصية', 'مراجعة منتظمة ومتابعة', 'حلقات جماعية ومحادثات'],
    featuresEn: ['Flexible daily schedules', 'Personalized plans', 'Regular review and follow-up', 'Group circles and discussions'],
  },
  {
    id: 'ijazah',
    icon: '🎓',
    title: 'إجازة القرآن',
    titleEn: 'Quran Ijazah',
    ageRange: 'حافظون للقرآن',
    ageRangeEn: 'Holy Quran Memorizers',
    color: '#eef2ff',
    accent: '#4338ca',
    desc: 'برنامج الإجازة بالسند المتصل برواية حفص عن عاصم، لمن أتمّ الحفظ ويرغب في نيل الإجازة.',
    descEn: 'Ijazah program with a connected chain of narration for those who have completed memorization.',
    features: ['سند متصل بالنبي ﷺ', 'معلمون مجازون فقط', 'اختبار ختامي رسمي', 'شهادة إجازة معتمدة'],
    featuresEn: ['Connected chain to the Prophet ﷺ', 'Certified ijazah teachers', 'Official final exam', 'Certified ijazah certificate'],
  },
  {
    id: 'tajweed',
    icon: '🎵',
    title: 'تجويد وتلاوة',
    titleEn: 'Tajweed & Recitation',
    ageRange: 'جميع المستويات',
    ageRangeEn: 'All Levels',
    color: '#fff0f0',
    accent: '#9f1239',
    desc: 'تعلّم أحكام التجويد من الصفر حتى الاتقان مع التطبيق العملي على آيات القرآن الكريم.',
    descEn: 'Learn tajweed rules from scratch to mastery with practical application on Quranic verses.',
    features: ['من الصفر للاحتراف', 'تسجيل وتقييم صوتي', 'أحكام التجويد كاملة', 'ممارسة مكثفة وتصحيح فوري'],
    featuresEn: ['From zero to master', 'Audio recording and evaluation', 'Complete tajweed rules', 'Intensive practice and instant correction'],
  },
];

// ── Pricing plans ─────────────────────────────────────────────────────────────
export const PLANS = [
  {
    id: 'trial',
    badge: null,
    title: 'حصة تجريبية',
    titleEn: 'Trial Session',
    price: 'مجاناً',
    priceEn: 'Free',
    priceNum: null,
    period: 'مرة واحدة',
    periodEn: 'One-time',
    features: [
      'حصة تجريبية واحدة',
      'نصف ساعة للحصة',
      'للأطفال والكبار',
      'طالب واحد',
    ],
    featuresEn: [
      'One trial session',
      '30 min session',
      'Kids & Adults',
      'One student',
    ],
    cta: 'ابدأ مجاناً',
    ctaEn: 'Start Free',
    highlight: false,
    color: '#064e3b',
  },
  {
    id: 'kids',
    badge: 'الأكثر طلباً',
    title: 'باقة الأطفال',
    titleEn: 'Kids Bundle',
    price: '٤٠٠',
    priceEn: '400',
    priceNum: 400,
    period: 'جنيه / شهر',
    periodEn: 'EGP / Month',
    features: [
      '٨ حصص (في الشهر)',
      'نصف ساعة للحصة',
      'للأطفال فقط',
      'طالب واحد',
    ],
    featuresEn: [
      '8 sessions (Monthly)',
      '30 min session',
      'Kids only',
      'One student',
    ],
    cta: 'اشترك الآن',
    ctaEn: 'Join Group',
    highlight: true,
    color: '#064e3b',
  },
  {
    id: 'adults',
    badge: null,
    title: 'باقة البالغين',
    titleEn: 'Adults Bundle',
    price: '٧٠٠',
    priceEn: '700',
    priceNum: 700,
    period: 'جنيه / شهر',
    periodEn: 'EGP / Month',
    features: [
      '٨ حصص (في الشهر)',
      'ساعة كاملة للحصة',
      'للبالغين',
      'طالبان',
    ],
    featuresEn: [
      '8 sessions (Monthly)',
      '1 hour session',
      'For adults',
      'Two students',
    ],
    cta: 'اشترك الآن',
    ctaEn: 'Join Group',
    highlight: false,
    color: '#064e3b',
  },
  {
    id: 'ijazah',
    badge: null,
    title: 'باقة الإجازة',
    titleEn: 'Ijazah Bundle',
    price: '١٢٠٠',
    priceEn: '1200',
    priceNum: 1200,
    period: 'جنيه / شهر',
    periodEn: 'EGP / Month',
    features: [
      '١٢ حصة (في الشهر)',
      'ساعة كاملة للحصة',
      'للحافظين فقط',
      'طالب واحد',
    ],
    featuresEn: [
      '12 sessions (Monthly)',
      '1 hour session',
      'For memorizers only',
      'One student',
    ],
    cta: 'اشترك الآن',
    ctaEn: 'Join Group',
    highlight: false,
    color: '#064e3b',
  },
];

// ── Teachers data ─────────────────────────────────────────────────────────────
export const TEACHERS = [
  {
    id: 1,
    name: 'الشيخ محمد الأزهري',
    nameEn: 'Sheikh Mohammed Al-Azhari',
    country: 'مصر',
    countryEn: 'Egypt',
    initials: 'م.أ',
    color: '#064e3b',
    lang: ['عربي'],
    langEn: ['Arabic'],
    teaches: ['تجويد وتلاوة', 'حفظ القرآن'],
    teachesEn: ['Tajweed', 'Quran Memorization'],
    rating: 4.9,
    students: 120,
  },
  {
    id: 2,
    name: 'الأستاذة فاطمة حسن',
    nameEn: 'Ms. Fatima Hassan',
    country: 'مصر',
    countryEn: 'Egypt',
    initials: 'ف.ح',
    color: '#b8941f',
    lang: ['عربي', 'English'],
    langEn: ['Arabic', 'English'],
    teaches: ['حفظ للأطفال'],
    teachesEn: ['Kids Memorization'],
    rating: 5.0,
    students: 95,
  },
  {
    id: 3,
    name: 'الشيخ أحمد عبد الله',
    nameEn: 'Sheikh Ahmed Abdullah',
    country: 'مصر',
    countryEn: 'Egypt',
    initials: 'أ.ع',
    color: '#4338ca',
    lang: ['عربي'],
    langEn: ['Arabic'],
    teaches: ['إجازة القرآن', 'تجويد'],
    teachesEn: ['Quran Ijazah', 'Tajweed'],
    rating: 4.9,
    students: 60,
  },
  {
    id: 4,
    name: 'الأستاذة نور الإسلام',
    nameEn: 'Ms. Nour Al-Islam',
    country: 'مصر',
    countryEn: 'Egypt',
    initials: 'ن.إ',
    color: '#9f1239',
    lang: ['عربي', 'Français'],
    langEn: ['Arabic', 'French'],
    teaches: ['حفظ للكبار'],
    teachesEn: ['Adult Memorization'],
    rating: 4.8,
    students: 88,
  },
  {
    id: 5,
    name: 'الشيخ يوسف الحسني',
    nameEn: 'Sheikh Youssef Al-Hasani',
    country: 'مصر',
    countryEn: 'Egypt',
    initials: 'ي.ح',
    color: '#065f46',
    lang: ['عربي', 'English'],
    langEn: ['Arabic', 'English'],
    teaches: ['تجويد وتلاوة'],
    teachesEn: ['Tajweed & Recitation'],
    rating: 5.0,
    students: 74,
  },
  {
    id: 6,
    name: 'الأستاذة مريم إبراهيم',
    nameEn: 'Ms. Maryam Ibrahim',
    country: 'مصر',
    countryEn: 'Egypt',
    initials: 'م.إ',
    color: '#b8941f',
    lang: ['عربي'],
    langEn: ['Arabic'],
    teaches: ['حفظ للأطفال', 'حفظ للكبار'],
    teachesEn: ['Kids', 'Adults'],
    rating: 4.9,
    students: 110,
  },
];

// ── Testimonials ──────────────────────────────────────────────────────────────
export const TESTIMONIALS = [
  {
    name: 'أم عبد الرحمن',
    nameEn: 'Um Abdulrahman',
    role: 'ولية أمر طالب',
    roleEn: 'Parent of a student',
    country: 'مصر',
    countryEn: 'Egypt',
    rating: 5,
    text: 'ابني حفظ ١٠ أجزاء في ستة أشهر مع منصة مُكث. المعلم صبور جداً والمنهج ممتاز، جزاهم الله خيراً.',
    textEn: 'My son memorized 10 parts in six months with Mukth. The teacher is very patient and the curriculum is excellent.',
    initials: 'أ.ع',
    color: '#064e3b',
  },
  {
    name: 'أحمد المنصوري',
    nameEn: 'Ahmed Al-Mansouri',
    role: 'طالب — باقة البالغين',
    roleEn: 'Student — Adult Bundle',
    country: 'السعودية',
    countryEn: 'Saudi Arabia',
    rating: 5,
    text: 'كنت مبتدئاً تماماً في التجويد. الآن أقرأ القرآن بأحكام الحمد لله. الجدول المرن ساعدني كثيراً مع ضغط العمل.',
    textEn: 'I was a complete beginner in Tajweed. Now I read the Quran correctly. The flexible schedule helped me a lot.',
    initials: 'أ.م',
    color: '#b8941f',
  },
  {
    name: 'سارة عبد الكريم',
    nameEn: 'Sarah Abdul Karim',
    role: 'طالبة — برنامج الإجازة',
    roleEn: 'Student — Ijazah Program',
    country: 'الإمارات',
    countryEn: 'UAE',
    rating: 5,
    text: 'نلت الإجازة برواية حفص بعد سنة ونصف. الشيخ المجاز كان دقيقاً ومتابعاً في كل حصة. تجربة لا تنسى.',
    textEn: 'I received my Ijazah after a year and a half. The certified Sheikh was precise and followed up in every class.',
    initials: 'س.ع',
    color: '#4338ca',
  },
  {
    name: 'عمر الشافعي',
    nameEn: 'Omar Al-Shafei',
    role: 'طالب — تجويد وتلاوة',
    roleEn: 'Student — Tajweed',
    country: 'مصر',
    countryEn: 'Egypt',
    rating: 5,
    text: 'منذ سنتين وأنا مع مُكث ولم أفكر في التغيير. الأسعار مناسبة جداً مقارنة بجودة التعليم والمعلمين.',
    textEn: 'I have been with Mukth for two years and never thought of changing. The prices are very suitable.',
    initials: 'ع.ش',
    color: '#9f1239',
  },
];
